version: '3.8'
services:
  db:
    container_name: testi
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '3306:3306'
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  