# Tarvii REST Client extensionin, että toimii
GET http://localhost:3001/api/accounts

###

GET http://localhost:3001/api/accounts/c2b50ca3-7455-4f30-898c-2763cde438e1

###

POST http://localhost:3001/api/accounts/signup HTTP/1.1
content-type: application/json

{
    "username": "Testaaja",
    "password": "asda2312L;;:sAa",
    "email": "Testaaja.Testaa@gmail.com"
}
###
POST http://localhost:3001/api/accounts/login HTTP/1.1
content-type: application/json

{
    "email": "Testaaja.Testaa@gmail.com",
    "password": "asda2312L;;:sAa"
}
###
POST http://localhost:3001/api/plants HTTP/1.1
content-type: application/json

{
    "name": "Jukkapalmu",
    "description": "Kiva palmukasvi",
    "price": "30",
    "image": "https://www.viherpeukalot.fi/images/products/12355-2_orig.jpg"
}