name: Backend-PullRequest

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches:
      - backend_branch
      - main
    paths:
      - backend/**

jobs:
run-tests:
  runs-on: ubuntu-latest
  services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
  steps:
    - name: Fetch code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      working-directory: ./backend
      run: npm install

    - name: Create database
      working-directory: ./backend
      run: |
          PGPASSWORD=postgres psql -U postgres -h 127.0.0.1 -p ${{ job.services.postgres.ports[5432] }} -d postgres < init.sql"
    - name: Running tests
        working-directory: ./backend
        run: npm run test
        #env:
        #TODO: Lisää env muuttujat

